"""Initial schema

Revision ID: ce9eea995a0e
Revises: 
Create Date: 2026-08-14 16:26:01.577756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9eea995a0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.String(length=10), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('fastf1_version', sa.String(length=20), nullable=True),
    sa.Column('pipeline_version', sa.String(length=20), nullable=True),
    sa.Column('row_count_laps', sa.Integer(), nullable=True),
    sa.Column('row_count_telemetry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metadata_session', 'dataset_metadata', ['year', 'event_name', 'session_type'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.String(length=10), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('circuit_key', sa.Integer(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_year_event', 'sessions', ['year', 'event_name', 'session_type'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('team_affiliation', sa.String(length=60), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_color', sa.String(length=7), nullable=True),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('team_color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index('ix_drivers_code', 'drivers', ['code'], unique=False)
    op.create_index('ix_drivers_session', 'drivers', ['session_id'], unique=False)
    op.create_table('weather',
    sa.Column('weather_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Integer(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_index('ix_weather_session', 'weather', ['session_id'], unique=False)
    op.create_table('laps',
    sa.Column('lap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=True),
    sa.Column('fuel_corrected_lap_time_ms', sa.Integer(), nullable=True),
    sa.Column('sector1_ms', sa.Integer(), nullable=True),
    sa.Column('sector2_ms', sa.Integer(), nullable=True),
    sa.Column('sector3_ms', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('stint_number', sa.Integer(), nullable=True),
    sa.Column('is_pit_lap', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('track_status', sa.String(length=10), nullable=True),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lap_id')
    )
    op.create_index('ix_laps_driver', 'laps', ['driver_id'], unique=False)
    op.create_index('ix_laps_driver_lap', 'laps', ['driver_id', 'lap_number'], unique=False)
    op.create_table('pitstops',
    sa.Column('pitstop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pitstop_id')
    )
    op.create_index('ix_pitstops_driver_session', 'pitstops', ['driver_id', 'session_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('input_features', sa.Text(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('ix_predictions_session_driver', 'predictions', ['session_id', 'driver_id'], unique=False)
    op.create_index('ix_predictions_type', 'predictions', ['prediction_type'], unique=False)
    op.create_table('stints',
    sa.Column('stint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('start_lap', sa.Integer(), nullable=True),
    sa.Column('end_lap', sa.Integer(), nullable=True),
    sa.Column('tyre_life_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stint_id')
    )
    op.create_index('ix_stints_driver_session', 'stints', ['driver_id', 'session_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('throttle_pct', sa.Float(), nullable=True),
    sa.Column('brake', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.Boolean(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_lap', 'telemetry', ['lap_id'], unique=False)
    op.create_index('ix_telemetry_lap_dist', 'telemetry', ['lap_id', 'distance_m'], unique=False)
    op.create_index('ix_telemetry_lap_time', 'telemetry', ['lap_id', 'time_ms'], unique=False)
    op.create_index('ix_telemetry_session', 'telemetry', ['session_id'], unique=False)
    op.create_table('tyres',
    sa.Column('tyre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('degradation_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tyre_id'),
    sa.UniqueConstraint('lap_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyres')
    op.drop_index('ix_telemetry_session', table_name='telemetry')
    op.drop_index('ix_telemetry_lap_time', table_name='telemetry')
    op.drop_index('ix_telemetry_lap_dist', table_name='telemetry')
    op.drop_index('ix_telemetry_lap', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('ix_stints_driver_session', table_name='stints')
    op.drop_table('stints')
    op.drop_index('ix_predictions_type', table_name='predictions')
    op.drop_index('ix_predictions_session_driver', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_pitstops_driver_session', table_name='pitstops')
    op.drop_table('pitstops')
    op.drop_index('ix_laps_driver_lap', table_name='laps')
    op.drop_index('ix_laps_driver', table_name='laps')
    op.drop_table('laps')
    op.drop_index('ix_weather_session', table_name='weather')
    op.drop_table('weather')
    op.drop_index('ix_drivers_session', table_name='drivers')
    op.drop_index('ix_drivers_code', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sessions_year_event', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_metadata_session', table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    # ### end Alembic commands ###
